functional:
  # Possible values: https://twig.symfony.com/doc/2.x/filters/date.html
  date_format: 'Y-m-d'
  # Used to calculate the duration of a audio file
  bitrate_kbps: 192
  # How many items are displayed per page
  item_limit: 10
legal:
  # Displayed in footer
  copyright: ''
  # Rendered in footer starts with https://
  imprint_url: ''
  # Displayed in footer
  imprint_link_name: ''
metadata:
  # Url to original website
  canonical_link: ''
messages:
  # Displayed if feed could not be fetched
  feed_error: 'No valid rss feed was supplied.'
  # Displayed if no results were found
  no_results: 'No results found.'

# Important: bitrate_kbps and item_limit are also configured in
# RssFeedController as a fallback and date_format is defined in
# the corresponding template as fallback.
